development:
  adapter: postgresql
  encoding: utf8
  database: development
  pool: 2
production:
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: production
test:
  adapter: postgresql
  database: database-test
  pool: 5
  encoding: utf8
  timeout: 5000